### ISSUE TITLE
Unable to docker build - git not found

### ISSUE THREAD

**Issue by algogrit** [tariksetia/go-auction-api#1]
The docker build fails with `golang:alpine`, it works with `golang:latest` though.
https://github.com/tariksetia/go-auction-api/blob/44ef0c3543124337ad5f822476cb4f5061759593/Dockerfile#L2

**Comment by tariksetia** [comment]
Thanks!. Golang:latest worked <though it was not working earlier, couldn't know why>
Added DEP as well
